### ISSUE TITLE
1. Database

### ISSUE THREAD

**Issue by PhamPhiTruong** [PhamPhiTruong/DotNET-REST-Coffee-Android#1]
RDBMS : MySQL
Database Diagram : 
    https://drive.google.com/file/d/1DF6kLdbr7OPlJJQuyPDbu95Be-l8B5WN/view

Các đối tượng :
+ User (Khách hàng)
+ Product (Sản phẩm)
+ Ingredient ( Phụ gia cho sản phẩm)
+ Cart (Giỏ hàng)
+ Order (Đơn hàng)

**Comment by TheEmpty123** [comment]
Finished
