### ISSUE TITLE
3. API Login

### ISSUE THREAD

**Issue by PhamPhiTruong** [PhamPhiTruong/DotNET-REST-Coffee-Android#3]
Mô tả : Xử lí các request liên quan đến đăng nhập, đăng kí
Cách sử dụng :

+ Đăng kí : Request là POST kèm theo Thông tin User muốn đăng kí (Đối tượng user đăng kí gồm tên, mail, mật khẩu) . Respond sẽ là "Đăng ký thành công." nếu thành công, "Đăng ký thành công." nếu thất bại kèm theo nguyên nhân đăng ký thất bại.
+ Đăng nhập : Request là POST kèm theo Thông tin User (Đối tượng user gồm mail, mật khẩu) . Respond sẽ là "Đăng nhập thành công." (Có thể kèm theo Token) nếu thành công, "Đăng nhập thất bại." nếu thất bại kèm theo nguyuên nhân đăng nhập thất bại.

**Comment by TheEmpty123** [comment]
Finished
