### ISSUE TITLE
4. API Product

### ISSUE THREAD

**Issue by PhamPhiTruong** [PhamPhiTruong/DotNET-REST-Coffee-Android#4]
Mô tả : Xử lí các request liên quan đến sản phẩm
Cách sử dụng :

+ Lấy danh sách sản phẩm: Request là GET. Respond sẽ là 1 kèm theo Danh sách sản phẩm (List ProductDTO), nếu thất bại trả về BadRequestResult.
+ Lấy danh sách sản phẩm theo id: Request là GET. Respond sẽ là 1 kèm theo Danh sách sản phẩm (List ProductDTO), nếu thất bại trả về BadRequestResult.
+ Lấy danh sách sản phẩm theo type: Request là GET. Respond sẽ là 1 kèm theo Danh sách sản phẩm (List ProductDTO), nếu thất bại trả về BadRequestResult.
+ Lấy danh sách sản phẩm theo category: Request là GET. Respond sẽ là 1 kèm theo Danh sách sản phẩm (List ProductDTO), nếu thất bại trả về BadRequestResult.
+ Thêm sản phẩm : Request là POST. Thêm vào 1 sản phẩm. Nếu sản phẩm đã tồn tại, trả về BadRequestResult.
+ Cập nhật sản phẩm: Request là PUT. Cập nhập 1 sản phẩm đã có sẵn, nếu sản phẩm không tồn tại, tạo 1 sản phẩm mới.
+ Xóa sản phẩm : Request là DELETE. Xóa 1 sản phẩm theo id.

**Comment by TheEmpty123** [comment]
Finished!
